apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: __GITHUB_REPO__
    targetRevision: main
    path: clusters/lab/workloads/ollama/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
